const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {createHarness,signed,canonical,hash,SHA}=require('../support/apps_script_harness.cjs');
const ID='execution:gd004:synthetic:'+SHA;
function scenario(){const h=createHarness();h.initialize();const snapshot=h.post(signed({operation:'get_execution_payload',executionId:ID,payload:{queue_row:2},requestId:'get:1'})).response.data;
 return {h,snapshot,bound:{queue_row:2,expected_payload_hash:snapshot.payload_hash}};}
function call(h,operation,payload,requestId=operation){return h.post(signed({operation,executionId:ID,payload,requestId})).response;}
function result(extra={}){const v={request_id:'browser:'+ID,execution_id:ID,operation:'browser_read',source_sha:SHA,provider:'github_hosted',started_at:new Date().toISOString(),completed_at:new Date().toISOString(),typed_status:'rendered',form_fingerprint:'form123',runtime_fingerprint:'runtime123',mutation_count:0,upload_count:0,submit_count:0,evidence_summary:'synthetic read-only',...extra};return {...v,result_hash:hash(canonical(v))};}

test('bootstrap is idempotent and never resets a claimed row',()=>{const {h,bound}=scenario();call(h,'claim',bound);const writes=h.state.writes;h.initialize();assert.equal(h.state.writes,writes);assert.equal(h.state.rows[1][2],'CLAIMED');});
test('real gateway verifies health; missing documented secret fails closed',()=>{const h=createHarness();assert.equal(h.post(signed()).response.data.status,'ok');h.state.props.delete('EJS_HMAC_SHARED_SECRET_TEST');h.state.props.set('EJS_GH_HMAC_SECRET','wrong-name');assert.equal(h.post(signed()).error_code,'GD004_HMAC_SECRET_NOT_CONFIGURED');});
test('signature tamper fails without Sheet mutation',()=>{const h=createHarness();const req=signed();req.signature='0'.repeat(64);assert.equal(h.post(req).response.error_code,'GD004_SIGNATURE_INVALID');assert.equal(h.state.writes,0);});
test('expired, wrong environment, and wrong deployed SHA reject',()=>{for(const [patch,code] of [[{created_at:new Date(Date.now()-200000).toISOString(),expires_at:new Date(Date.now()-10000).toISOString()},'GD004_REQUEST_EXPIRED'],[{environment:'PROD'},'GD004_ENVIRONMENT_NOT_TEST'],[{source_sha:'b'.repeat(40)},'GD004_SOURCE_SHA_NOT_DEPLOYED']]){const h=createHarness();assert.equal(h.post(signed(patch)).response.error_code,code);assert.equal(h.state.writes,0);}});
test('exact/fresh-nonce retries are no-ops; changed request identity rejects',()=>{const h=createHarness();const req=signed();assert.equal(h.post(req).response.data.exact_replay,false);assert.equal(h.post(req).response.data.exact_replay,true);assert.equal(h.post(signed()).response.data.exact_replay,true);assert.equal(h.post(signed({executionId:'other'})).response.error_code,'GD004_REQUEST_ID_PAYLOAD_COLLISION');});
test('a nonce cannot be shared between different requests',()=>{const h=createHarness();h.post(signed({nonce:'same'}));assert.equal(h.post(signed({nonce:'same',requestId:'different'})).response.error_code,'GD004_NONCE_REPLAY_COLLISION');});
test('mutating or non-boolean capabilities reject',()=>{for(const flags of [{browser_read:true,form_value_write:true,approved_file_upload:false,final_submit:false},{browser_read:'true',form_value_write:false,approved_file_upload:false,final_submit:false}]){const h=createHarness();assert.equal(h.post(signed({capability_flags:flags})).response.ok,false);}});
test('TEST title and exact header are checked before queue access',()=>{const {h}=scenario();h.state.spreadsheetTitle='EU Job Tracker';assert.equal(call(h,'get_execution_payload',{queue_row:2}).ok,false);h.state.spreadsheetTitle='TEST_EU_Job_Tracker';h.state.rows[0][0]='wrong';assert.equal(call(h,'get_execution_payload',{queue_row:2},'get:2').error_code,'GD004_QUEUE_HEADER_MISMATCH');});
test('wrong row, wrong execution and stale payload all fail closed',()=>{const {h,bound}=scenario();assert.equal(call(h,'claim',{...bound,queue_row:3}).error_code,'GD004_QUEUE_ROW_MISSING');assert.equal(call(h,'claim',{...bound,expected_payload_hash:'0'.repeat(64)},'claim:2').error_code,'GD004_STALE_QUEUE_SNAPSHOT');h.state.rows[1][0]='another';assert.equal(call(h,'claim',bound,'claim:3').error_code,'GD004_QUEUE_IDENTITY_MISMATCH');});
test('claim has one winner and a duplicate does not write',()=>{const {h,bound}=scenario();assert.equal(call(h,'claim',bound).data.claim_state,'claimed');const writes=h.state.writes;assert.equal(call(h,'claim',bound,'claim:2').data.claim_state,'replay');assert.equal(h.state.writes,writes);});
test('concurrent claim fails without changing the row',()=>{const {h,bound}=scenario();h.state.lock=true;assert.equal(call(h,'claim',bound).ok,false);assert.equal(h.state.rows[1][2],'READY');});
test('corrupt independent write readback is detected',()=>{const {h,bound}=scenario();h.state.corruptReadback=true;assert.equal(call(h,'claim',bound).error_code,'GD004_QUEUE_READBACK_MISMATCH');});
test('approved synthetic PDF returns exact bytes only after claim',()=>{const {h,bound,snapshot}=scenario();const payload={...bound,artifact_id:snapshot.execution_payload.approved_assets[0].artifact_id};assert.equal(call(h,'get_approved_asset',payload,'asset:0').error_code,'GD004_ASSET_REQUIRES_CLAIM');assert.equal(h.state.fileReads,0);call(h,'claim',bound);const data=call(h,'get_approved_asset',payload,'asset:1').data;assert.equal(hash(Buffer.from(data.base64_data,'base64')),data.asset.sha256);});
test('unapproved asset cannot cause Drive access',()=>{const {h,bound}=scenario();call(h,'claim',bound);assert.equal(call(h,'get_approved_asset',{...bound,artifact_id:'unknown'}).error_code,'GD004_ASSET_NOT_APPROVED_FOR_EXECUTION');assert.equal(h.state.fileReads,0);});
test('asset folder, metadata and changed bytes reject',()=>{for(const change of [h=>h.state.folder='outside',h=>h.state.filename='changed.pdf',h=>{h.state.bytes=Buffer.from(h.state.bytes);h.state.bytes[100]^=1;}]){const {h,bound,snapshot}=scenario();call(h,'claim',bound);change(h);assert.equal(call(h,'get_approved_asset',{...bound,artifact_id:snapshot.execution_payload.approved_assets[0].artifact_id}).ok,false);}});
test('reconcile binds identity, enforces zero side effects and rejects extra fields',()=>{for(const patch of [{execution_id:'other'},{mutation_count:1},{upload_count:'0'},{private_payload:'should never be stored'}]){const {h,bound}=scenario();call(h,'claim',bound);assert.equal(call(h,'reconcile_result',{...bound,result:result(patch)}).ok,false);assert.equal(h.state.rows[1][2],'CLAIMED');}});
test('durable result replay is idempotent; different result cannot replace it',()=>{const {h,bound}=scenario();call(h,'claim',bound);const r=result();assert.equal(call(h,'reconcile_result',{...bound,result:r}).data.queue_state,'COMPLETED');const writes=h.state.writes;assert.equal(call(h,'reconcile_result',{...bound,result:r},'result:2').data.reconcile_state,'replay');assert.equal(h.state.writes,writes);assert.equal(call(h,'reconcile_result',{...bound,result:result({typed_status:'access_blocked'})},'result:3').error_code,'GD004_RESULT_COLLISION');});
test('blocked browser result goes to review, never completed or Applied',()=>{const {h,bound}=scenario();call(h,'claim',bound);assert.equal(call(h,'reconcile_result',{...bound,result:result({typed_status:'access_blocked'})}).data.queue_state,'REVIEW_REQUIRED');});
test('result cannot be reconciled without a claim',()=>{const {h,bound}=scenario();assert.equal(call(h,'reconcile_result',{...bound,result:result()}).error_code,'GD004_EXECUTION_NOT_CLAIMED');});
test('request size is bounded',()=>{const h=createHarness();assert.equal(h.post(signed({payload:{long:'x'.repeat(33000)}})).error_code,'GD004_REQUEST_TOO_LARGE');});
test('bootstrap documentation, workflow and code share the HMAC property name',()=>{const root=path.resolve(__dirname,'../..');const doc=fs.readFileSync(path.join(root,'docs/GD004_ZERO_COST_APPS_SCRIPT_BOOTSTRAP.md'),'utf8');assert.ok(doc.includes('EJS_HMAC_SHARED_SECRET_TEST'));assert.ok(!doc.includes('EJS_GH_HMAC_SECRET'));const manifest=JSON.parse(fs.readFileSync(path.join(root,'google_native/apps_script_zero_cost/appsscript.json')));assert.deepEqual(manifest.oauthScopes.sort(),['https://www.googleapis.com/auth/drive.readonly','https://www.googleapis.com/auth/spreadsheets'].sort());});

test('duplicate execution ID in another queue row cannot run twice',()=>{const {h,bound}=scenario();h.state.rows.push([...h.state.rows[1]]);assert.equal(call(h,'claim',bound).error_code,'GD004_EXECUTION_ID_NOT_UNIQUE');assert.equal(h.state.rows[1][2],'READY');});
